### ISSUE TITLE
Not able to provision Azure resources

### ISSUE THREAD

**Issue by Vivihung** [Azure-Samples/locutus#1]
Got an error when setup the infrastructure. Wondering if there's any subscription/SKU requirements.

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Clone the repo, then run `./provision.ps1 -name buildlocutus -location westus2`

### Any log messages given by the failure
![image](https://user-images.githubusercontent.com/4814277/167957551-7774f6af-ce12-4a22-80ef-4f1c6f02d861.png)

### Expected/desired behavior
Create Azure instances without error.

### OS and Version?
Windows 11

**Comment by sethjuarez** [comment]
Closing with instructions added to docs. Feel free to reopen if we've missed something!
