### ISSUE TITLE
Documentation missing azure login and subscription selection

### ISSUE THREAD

**Issue by CameronVetter** [Azure-Samples/locutus#3]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Following the page https://github.com/Azure-Samples/locutus/wiki, it never tells the user to login and select their subscription.
> I spent an embarrassing amount of time being confused why the quota error messages didn't match the quota of the subscription I imagined I was working against.

### Expected/desired behavior
> Add some instructions to have the user do an az login followed by an az account set command

**Comment by sethjuarez** [comment]
Great catch!

**Comment by sethjuarez** [comment]
Added detailed instructions - thanks for the suggestion
