### ISSUE TITLE
train.ipynb unable to find config.json file

### ISSUE THREAD

**Issue by CameronVetter** [Azure-Samples/locutus#4]
### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Run Model.ipynb to generate the model folder
> Run train.ipynb which will fail on cell 12 because the config.json file is missing from the model/tokenizer folder

### Any log messages given by the failure
> unable to load XXX/model/tokenizer/config.json

### Expected/desired behavior
> loads and notebook continues

### OS and Version?
> Azure Notebook
### Mention any other details that might be useful

PR coming with a fix...

**Comment by sethjuarez** [comment]
Closing with fix
