### ISSUE TITLE
unexpected keyword argument 'preprocess_logits_for_metrics'

### ISSUE THREAD

**Issue by CameronVetter** [Azure-Samples/locutus#6]
### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> run model.ipynb to create models folder
> run train.ipynb to train, and failure occurs on cell 15

### Any log messages given by the failure

Requirement already satisfied: datasets in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (1.8.0)
Requirement already satisfied: requests>=2.19.0 in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (from datasets) (2.27.1)
Requirement already satisfied: pyarrow<4.0.0,>=1.0.0 in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (from datasets) (3.0.0)
Requirement already satisfied: dill in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (from datasets) (0.3.4)
Requirement already satisfied: fsspec in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (from datasets) (2022.3.0)
Requirement already satisfied: tqdm<4.50.0,>=4.27 in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (from datasets) (4.49.0)
Requirement already satisfied: packaging in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (from datasets) (21.3)
Requirement already satisfied: huggingface-hub<0.1.0 in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (from datasets) (0.0.19)
Requirement already satisfied: pandas in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (from datasets) (1.1.5)
Requirement already satisfied: numpy>=1.17 in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (from datasets) (1.19.0)
Requirement already satisfied: multiprocess in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (from datasets) (0.70.12.2)
Requirement already satisfied: xxhash in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (from datasets) (3.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (from requests>=2.19.0->datasets) (1.26.7)
Requirement already satisfied: charset-normalizer~=2.0.0; python_version >= "3" in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (from requests>=2.19.0->datasets) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (from requests>=2.19.0->datasets) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5; python_version >= "3" in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (from requests>=2.19.0->datasets) (3.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (from packaging->datasets) (3.0.8)
Requirement already satisfied: pyyaml in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (from huggingface-hub<0.1.0->datasets) (6.0)
Requirement already satisfied: typing-extensions in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (from huggingface-hub<0.1.0->datasets) (4.2.0)
Requirement already satisfied: filelock in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (from huggingface-hub<0.1.0->datasets) (3.6.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2017.2 in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (from pandas->datasets) (2021.3)
Requirement already satisfied: six>=1.5 in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas->datasets) (1.16.0)
Note: you may need to restart the kernel to use updated packages.
[{'title': 'The Iliad, by Homer',
  'source': '6130-0.txt',
  'start': 4133,
  'end': 23285,
  'ignore': {'startswith': ['[Illustration:', 'BOOK', 'ARGUMENT'],
   'isupper': True},
  'replace': {'\\[\\d+\\]': ''}},
 {'title': 'The Odyssey, by Homer',
  'source': 'pg1727.txt',
  'start': 740,
  'end': 10833,
  'ignore': {'startswith': 'BOOK', 'isupper': True}}]
processing 'The Iliad, by Homer'
Using /mnt/batch/tasks/shared/LS_root/mounts/clusters/compute-24rg/code/Users/cameron/locutus/data/6130-0.txt... done!
processing 'The Odyssey, by Homer'
Using /mnt/batch/tasks/shared/LS_root/mounts/clusters/compute-24rg/code/Users/cameron/locutus/data/pg1727.txt... done!
Using custom data configuration default-9bae83752fc01f30
Downloading and preparing dataset text/default (download: Unknown size, generated: Unknown size, post-processed: Unknown size, total: Unknown size) to /mnt/batch/tasks/shared/LS_root/mounts/clusters/compute-24rg/code/Users/cameron/locutus/model/.cache/text/default-9bae83752fc01f30/0.0.0/e16f44aa1b321ece1f87b07977cc5d70be93d69b20486d6dacd62e12cf25c9a5...
Dataset text downloaded and prepared to /mnt/batch/tasks/shared/LS_root/mounts/clusters/compute-24rg/code/Users/cameron/locutus/model/.cache/text/default-9bae83752fc01f30/0.0.0/e16f44aa1b321ece1f87b07977cc5d70be93d69b20486d6dacd62e12cf25c9a5. Subsequent calls will reuse this data.
Embedding(50257, 768)
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Running tokenizer on dataset

Running tokenizer on dataset

Grouping texts in chunks of 256

Grouping texts in chunks of 256

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [15], in <cell line: 4>()
      1 from transformers import Trainer, default_data_collator, is_torch_tpu_available
      3 # Initialize our Trainer
----> 4 trainer = Trainer(
      5     model=model,
      6     args=training_args,
      7     train_dataset=train_dataset if training_args.do_train else None,
      8     eval_dataset=eval_dataset if training_args.do_eval else None,
      9     tokenizer=tokenizer,
     10     # Data collator will default to DataCollatorWithPadding, so we change it.
     11     data_collator=default_data_collator,
     12     compute_metrics=compute_metrics if training_args.do_eval and not is_torch_tpu_available() else None,
     13     preprocess_logits_for_metrics=preprocess_logits_for_metrics
     14     if training_args.do_eval and not is_torch_tpu_available()
     15     else None,
     16 )

TypeError: __init__() got an unexpected keyword argument 'preprocess_logits_for_metrics'

### Expected/desired behavior
> training completes

### OS and Version?
> Azure Notebooks

### Versions
> NA

### Mention any other details that might be useful
> To get this far you must correct issue #4 first

**Comment by CameronVetter** [comment]
Update for this issue, this is really a documentation issue.  In the page:

https://github.com/Azure-Samples/locutus/wiki/Notebooks

It tells the user to switch to "Python 3.8 - Pytorch and Tensorflow" after loading model.ipynb, but when the user opens train.ipynb the notebook defaults to "Python 3". The user needs to switch kernels for this one as well.  This is a bit of a silly error on my part, but I would guess others will make the same mistake.

**Comment by sethjuarez** [comment]
Added the clarification! Thanks for the heads up.
