### ISSUE TITLE
Pipeline node name should be a valid python identifier

### ISSUE THREAD

**Issue by CameronVetter** [Azure-Samples/locutus#8]
### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Build  the pipeline per the steps on this page: https://github.com/Azure-Samples/locutus/wiki/Finetuning
>The error will occur when executing: 
az ml job create -f cloud/pipeline.yml

### Any log messages given by the failure
>Met error <class 'marshmallow.exceptions.ValidationError'>:Validation for PipelineJobSchema failed:
>
> {
  "jobs": {
    "finetune-ptca": {
      "key": [
        "Pipeline node name should be a valid python identifier(lower letters, numbers, underscore and start with a letter or underscore). Currently got finetune-ptca."
      ]
    },
    "register-model": {
      "key": [
        "Pipeline node name should be a valid python identifier(lower letters, numbers, underscore and start with a letter or underscore). Currently got register-model."
      ]
    }
  }
}
>
>If you are trying to configure a job that is not of type pipeline, please specify the correct job type in the 'type' property.
For a more detailed breakdown of the PipelineJob schema, please see: https://aka.ms/ml-cli-v2-job-pipeline-yaml-reference.
The easiest way to author a specification file is using IntelliSense and auto-completion Azure ML VS code extension provides: https://code.visualstudio.com/docs/datascience/azure-machine-learning
To set up: https://docs.microsoft.com/azure/machine-learning/how-to-setup-vs-code
Please check log in debug mode for more details.

### Expected/desired behavior
> pipeline creation

### OS and Version?
> Windows 11 az ml CLI

### Versions
> {
  "azure-cli": "2.37.0",
  "azure-cli-core": "2.37.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ml": "2.4.1"
  }

**Comment by sethjuarez** [comment]
Interesting. I also ran into this issue (seems like the implementation changed before release). Thanks for the heads up.
